name: Dependencies

on:
  schedule:
    - cron: '0 0 * * 1'  # Run weekly
  workflow_dispatch:

jobs:
  dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          
      - name: Update dependencies
        run: npx npm-check-updates -u
        
      - name: Install dependencies
        run: npm install
        
      - name: Run tests
        run: npm test
        
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore(deps): update dependencies'
          title: '⬆️ Update dependencies'
          body: |
            Automated dependency updates.
            
            Please review the changes and merge if all tests pass.
          branch: deps/update
          delete-branch: true
          labels: dependencies 